export const airport=[
    {
        "id": "235",
        "IATA": "AHJ",
        "ICAO": "",
        "name": "红原机场",
        "city": "阿坝",
        "city_code": "AHJ",
        "province": "四川",
        "level": "",
        "latitude": "32.53",
        "longitude": "102.36",
        "website": ""
    },
    {
        "id": "236",
        "IATA": "AYN",
        "ICAO": "",
        "name": "安阳机场",
        "city": "安阳",
        "city_code": "AYN",
        "province": "河南",
        "level": "",
        "latitude": "36.1",
        "longitude": "114.35",
        "website": ""
    },
    {
        "id": "237",
        "IATA": "HSC",
        "ICAO": "",
        "name": "韶关桂头机场",
        "city": "韶关",
        "city_code": "HSC",
        "province": "广东",
        "level": "",
        "latitude": "24.25",
        "longitude": "113.25",
        "website": ""
    },
    {
        "id": "238",
        "IATA": "HCJ",
        "ICAO": "",
        "name": "河池金城江机场",
        "city": "河池",
        "city_code": "HCJ",
        "province": "广西",
        "level": "",
        "latitude": "24.78",
        "longitude": "107.7",
        "website": ""
    },
    {
        "id": "239",
        "IATA": "XNT",
        "ICAO": "",
        "name": "邢台褡裢机场",
        "city": "邢台",
        "city_code": "XNT",
        "province": "河北",
        "level": "",
        "latitude": "37.1",
        "longitude": "114.5",
        "website": ""
    },
    {
        "id": "240",
        "IATA": "AAT",
        "ICAO": "",
        "name": "阿勒泰机场",
        "city": "阿勒泰",
        "city_code": "AAT",
        "province": "新疆",
        "level": "",
        "latitude": "47.75",
        "longitude": "88.08",
        "website": ""
    },
    {
        "id": "241",
        "IATA": "ACX",
        "ICAO": "",
        "name": "兴义万峰林机场",
        "city": "兴义",
        "city_code": "ACX",
        "province": "贵州",
        "level": "",
        "latitude": "25.09",
        "longitude": "104.96",
        "website": ""
    },
    {
        "id": "242",
        "IATA": "AKU",
        "ICAO": "",
        "name": "温宿阿克苏机场",
        "city": "阿克苏",
        "city_code": "AKU",
        "province": "新疆",
        "level": "",
        "latitude": "41.26",
        "longitude": "80.29",
        "website": ""
    },
    {
        "id": "243",
        "IATA": "AKA",
        "ICAO": "",
        "name": "安康富强机场",
        "city": "安康",
        "city_code": "AKA",
        "province": "陕西",
        "level": "",
        "latitude": "32.71",
        "longitude": "108.94",
        "website": ""
    },
    {
        "id": "244",
        "IATA": "AQG",
        "ICAO": "",
        "name": "安庆天柱山机场",
        "city": "安庆",
        "city_code": "AQG",
        "province": "安徽",
        "level": "",
        "latitude": "30.58",
        "longitude": "117.05",
        "website": ""
    },
    {
        "id": "245",
        "IATA": "AOG",
        "ICAO": "",
        "name": "鞍山军用机场",
        "city": "鞍山",
        "city_code": "AOG",
        "province": "辽宁",
        "level": "",
        "latitude": "41.1",
        "longitude": "122.86",
        "website": ""
    },
    {
        "id": "246",
        "IATA": "AEB",
        "ICAO": "",
        "name": "百色巴马机场",
        "city": "百色",
        "city_code": "AEB",
        "province": "广西",
        "level": "",
        "latitude": "23.72",
        "longitude": "106.97",
        "website": ""
    },
    {
        "id": "247",
        "IATA": "RLK",
        "ICAO": "",
        "name": "巴彦淖尔天吉泰机场",
        "city": "巴彦淖尔",
        "city_code": "RLK",
        "province": "内蒙古",
        "level": "",
        "latitude": "40.93",
        "longitude": "107.74",
        "website": ""
    },
    {
        "id": "248",
        "IATA": "RKZ",
        "ICAO": "",
        "name": "和平机场",
        "city": "日喀则",
        "city_code": "RKZ",
        "province": "西藏",
        "level": "",
        "latitude": "29.35",
        "longitude": "89.31",
        "website": ""
    },
    {
        "id": "249",
        "IATA": "AXF",
        "ICAO": "",
        "name": "阿拉善左旗巴彦浩特机场",
        "city": "阿拉善左旗",
        "city_code": "AXF",
        "province": "内蒙古",
        "level": "",
        "latitude": "38.82",
        "longitude": "105.63",
        "website": ""
    },
    {
        "id": "250",
        "IATA": "AVA",
        "ICAO": "",
        "name": "黄果树机场",
        "city": "安顺",
        "city_code": "AVA",
        "province": "贵州",
        "level": "",
        "latitude": "26.26",
        "longitude": "105.87",
        "website": ""
    },
    {
        "id": "251",
        "IATA": "BPX",
        "ICAO": "",
        "name": "昌都邦达机场",
        "city": "昌都",
        "city_code": "BPX",
        "province": "西藏",
        "level": "",
        "latitude": "30.56",
        "longitude": "97.11",
        "website": ""
    },
    {
        "id": "252",
        "IATA": "BAV",
        "ICAO": "",
        "name": "包头机场",
        "city": "包头",
        "city_code": "BAV",
        "province": "内蒙古",
        "level": "",
        "latitude": "40.56",
        "longitude": "110",
        "website": ""
    },
    {
        "id": "253",
        "IATA": "BFJ",
        "ICAO": "",
        "name": "毕节飞雄机场",
        "city": "毕节",
        "city_code": "BFJ",
        "province": "贵州",
        "level": "",
        "latitude": "27.27",
        "longitude": "105.47",
        "website": ""
    },
    {
        "id": "254",
        "IATA": "BPL",
        "ICAO": "",
        "name": "阿拉山口机场",
        "city": "博乐",
        "city_code": "BPL",
        "province": "新疆",
        "level": "",
        "latitude": "44.9",
        "longitude": "82.02",
        "website": ""
    },
    {
        "id": "255",
        "IATA": "BSD",
        "ICAO": "",
        "name": "保山云瑞机场",
        "city": "保山",
        "city_code": "BSD",
        "province": "云南",
        "level": "",
        "latitude": "25.06",
        "longitude": "99.16",
        "website": ""
    },
    {
        "id": "256",
        "IATA": "CGD",
        "ICAO": "",
        "name": "常德桃花源机场",
        "city": "常德",
        "city_code": "CGD",
        "province": "湖南",
        "level": "",
        "latitude": "28.92",
        "longitude": "111.64",
        "website": ""
    },
    {
        "id": "257",
        "IATA": "CIH",
        "ICAO": "",
        "name": "长治王村机场",
        "city": "长治",
        "city_code": "CIH",
        "province": "山西",
        "level": "",
        "latitude": "36.25",
        "longitude": "113.12",
        "website": ""
    },
    {
        "id": "258",
        "IATA": "CHG",
        "ICAO": "",
        "name": "朝阳机场",
        "city": "朝阳",
        "city_code": "CHG",
        "province": "辽宁",
        "level": "",
        "latitude": "41.55",
        "longitude": "120.44",
        "website": ""
    },
    {
        "id": "259",
        "IATA": "CIF",
        "ICAO": "",
        "name": "赤峰玉龙机场",
        "city": "赤峰",
        "city_code": "CIF",
        "province": "内蒙古",
        "level": "",
        "latitude": "42.15",
        "longitude": "118.83",
        "website": ""
    },
    {
        "id": "260",
        "IATA": "CZX",
        "ICAO": "",
        "name": "常州奔牛国际机场",
        "city": "常州",
        "city_code": "CZX",
        "province": "江苏",
        "level": "",
        "latitude": "31.91",
        "longitude": "119.78",
        "website": ""
    },
    {
        "id": "261",
        "IATA": "DLU",
        "ICAO": "",
        "name": "大理荒草坝机场",
        "city": "大理",
        "city_code": "DLU",
        "province": "云南",
        "level": "",
        "latitude": "25.65",
        "longitude": "100.32",
        "website": ""
    },
    {
        "id": "262",
        "IATA": "DDG",
        "ICAO": "",
        "name": "丹东浪头国际机场",
        "city": "丹东",
        "city_code": "DDG",
        "province": "辽宁",
        "level": "",
        "latitude": "40.03",
        "longitude": "124.28",
        "website": ""
    },
    {
        "id": "263",
        "IATA": "DCY",
        "ICAO": "",
        "name": "稻城亚丁机场",
        "city": "稻城",
        "city_code": "DCY",
        "province": "四川",
        "level": "",
        "latitude": "29.32",
        "longitude": "100.05",
        "website": ""
    },
    {
        "id": "264",
        "IATA": "DQA",
        "ICAO": "",
        "name": "大庆萨尔图机场",
        "city": "大庆",
        "city_code": "DQA",
        "province": "黑龙江",
        "level": "",
        "latitude": "46.75",
        "longitude": "125.15",
        "website": ""
    },
    {
        "id": "265",
        "IATA": "DAT",
        "ICAO": "",
        "name": "大同云冈机场",
        "city": "大同",
        "city_code": "DAT",
        "province": "山西",
        "level": "",
        "latitude": "40.06",
        "longitude": "113.48",
        "website": ""
    },
    {
        "id": "266",
        "IATA": "DAX",
        "ICAO": "",
        "name": "河市机场",
        "city": "达州",
        "city_code": "DAX",
        "province": "四川",
        "level": "",
        "latitude": "31.14",
        "longitude": "107.43",
        "website": ""
    },
    {
        "id": "267",
        "IATA": "DSN",
        "ICAO": "",
        "name": "鄂尔多斯伊金霍洛机场",
        "city": "鄂尔多斯",
        "city_code": "DSN",
        "province": "内蒙古",
        "level": "",
        "latitude": "39.5",
        "longitude": "109.86",
        "website": ""
    },
    {
        "id": "268",
        "IATA": "DOY",
        "ICAO": "",
        "name": "东营机场",
        "city": "东营",
        "city_code": "DOY",
        "province": "山东",
        "level": "",
        "latitude": "37.52",
        "longitude": "118.79",
        "website": ""
    },
    {
        "id": "269",
        "IATA": "DNH",
        "ICAO": "",
        "name": "敦煌机场",
        "city": "敦煌",
        "city_code": "DNH",
        "province": "甘肃",
        "level": "",
        "latitude": "40.2",
        "longitude": "94.68",
        "website": ""
    },
    {
        "id": "270",
        "IATA": "EJN",
        "ICAO": "",
        "name": "额济纳旗桃来机场",
        "city": "阿拉善额济纳旗",
        "city_code": "AXF",
        "province": "内蒙古",
        "level": "",
        "latitude": "42.02",
        "longitude": "101",
        "website": ""
    },
    {
        "id": "271",
        "IATA": "ENH",
        "ICAO": "",
        "name": "恩施许家坪机场",
        "city": "恩施",
        "city_code": "ENH",
        "province": "湖北",
        "level": "",
        "latitude": "30.32",
        "longitude": "109.48",
        "website": ""
    },
    {
        "id": "272",
        "IATA": "ERL",
        "ICAO": "",
        "name": "二连浩特赛乌苏国际机场",
        "city": "二连浩特",
        "city_code": "ERL",
        "province": "内蒙古",
        "level": "",
        "latitude": "43.43",
        "longitude": "112.1",
        "website": ""
    },
    {
        "id": "273",
        "IATA": "FUO",
        "ICAO": "",
        "name": "佛山沙堤机场",
        "city": "佛山",
        "city_code": "FUO",
        "province": "广东",
        "level": "",
        "latitude": "23.08",
        "longitude": "113.07",
        "website": ""
    },
    {
        "id": "274",
        "IATA": "ENY",
        "ICAO": "",
        "name": "延安二十里堡机场",
        "city": "延安",
        "city_code": "ENY",
        "province": "陕西",
        "level": "",
        "latitude": "36.48",
        "longitude": "109.46",
        "website": ""
    },
    {
        "id": "275",
        "IATA": "GOQ",
        "ICAO": "",
        "name": "格尔木机场",
        "city": "格尔木",
        "city_code": "GOQ",
        "province": "青海",
        "level": "",
        "latitude": "36.4",
        "longitude": "94.79",
        "website": ""
    },
    {
        "id": "276",
        "IATA": "GYS",
        "ICAO": "",
        "name": "广元盘龙机场",
        "city": "广元",
        "city_code": "GYS",
        "province": "四川",
        "level": "",
        "latitude": "32.4",
        "longitude": "105.7",
        "website": ""
    },
    {
        "id": "277",
        "IATA": "GYU",
        "ICAO": "",
        "name": "固原六盘山机场",
        "city": "固原",
        "city_code": "GYU",
        "province": "宁夏",
        "level": "",
        "latitude": "36.08",
        "longitude": "106.22",
        "website": ""
    },
    {
        "id": "278",
        "IATA": "HLD",
        "ICAO": "",
        "name": "呼伦贝尔东山国际机场",
        "city": "海拉尔",
        "city_code": "HLD",
        "province": "内蒙古",
        "level": "",
        "latitude": "49.21",
        "longitude": "119.82",
        "website": ""
    },
    {
        "id": "279",
        "IATA": "HDG",
        "ICAO": "",
        "name": "河北邯郸机场",
        "city": "邯郸",
        "city_code": "HDG",
        "province": "河北",
        "level": "",
        "latitude": "36.53",
        "longitude": "114.42",
        "website": ""
    },
    {
        "id": "280",
        "IATA": "HIA",
        "ICAO": "",
        "name": "淮安涟水机场",
        "city": "淮安",
        "city_code": "HIA",
        "province": "江苏",
        "level": "",
        "latitude": "33.79",
        "longitude": "119.13",
        "website": ""
    },
    {
        "id": "281",
        "IATA": "HJJ",
        "ICAO": "",
        "name": "怀化怀化芷江机场",
        "city": "怀化",
        "city_code": "HJJ",
        "province": "湖南",
        "level": "",
        "latitude": "27.44",
        "longitude": "109.7",
        "website": ""
    },
    {
        "id": "282",
        "IATA": "HLH",
        "ICAO": "",
        "name": "乌兰浩特义勒力特机场",
        "city": "乌兰浩特",
        "city_code": "HLH",
        "province": "内蒙古",
        "level": "",
        "latitude": "46.19",
        "longitude": "122",
        "website": ""
    },
    {
        "id": "283",
        "IATA": "HMI",
        "ICAO": "",
        "name": "哈密机场",
        "city": "哈密",
        "city_code": "HMI",
        "province": "新疆",
        "level": "",
        "latitude": "42.92",
        "longitude": "93.42",
        "website": ""
    },
    {
        "id": "284",
        "IATA": "HPG",
        "ICAO": "",
        "name": "神农架红坪机场",
        "city": "神农架",
        "city_code": "HPG",
        "province": "湖北",
        "level": "",
        "latitude": "31.63",
        "longitude": "110.34",
        "website": ""
    },
    {
        "id": "285",
        "IATA": "HTN",
        "ICAO": "",
        "name": "和田机场",
        "city": "和田",
        "city_code": "HTN",
        "province": "新疆",
        "level": "",
        "latitude": "37.04",
        "longitude": "79.87",
        "website": ""
    },
    {
        "id": "286",
        "IATA": "JGS",
        "ICAO": "",
        "name": "井冈山机场",
        "city": "井冈山",
        "city_code": "JGS",
        "province": "江西",
        "level": "",
        "latitude": "26.9",
        "longitude": "114.74",
        "website": ""
    },
    {
        "id": "287",
        "IATA": "JGD",
        "ICAO": "",
        "name": "加格达奇机场",
        "city": "加格达奇",
        "city_code": "JGD",
        "province": "黑龙江",
        "level": "",
        "latitude": "50.37",
        "longitude": "124.12",
        "website": ""
    },
    {
        "id": "288",
        "IATA": "JMU",
        "ICAO": "",
        "name": "佳木斯东郊机场",
        "city": "佳木斯",
        "city_code": "JMU",
        "province": "黑龙江",
        "level": "",
        "latitude": "46.85",
        "longitude": "130.46",
        "website": ""
    },
    {
        "id": "289",
        "IATA": "JGN",
        "ICAO": "",
        "name": "嘉峪关机场",
        "city": "嘉峪关",
        "city_code": "JGN",
        "province": "甘肃",
        "level": "",
        "latitude": "39.83",
        "longitude": "98.42",
        "website": ""
    },
    {
        "id": "290",
        "IATA": "JIC",
        "ICAO": "",
        "name": "金昌金川机场",
        "city": "金昌",
        "city_code": "JIC",
        "province": "甘肃",
        "level": "",
        "latitude": "38.54",
        "longitude": "102.35",
        "website": ""
    },
    {
        "id": "291",
        "IATA": "JDZ",
        "ICAO": "",
        "name": "景德镇罗家机场",
        "city": "景德镇",
        "city_code": "JDZ",
        "province": "江西",
        "level": "",
        "latitude": "29.34",
        "longitude": "117.18",
        "website": ""
    },
    {
        "id": "292",
        "IATA": "JHG",
        "ICAO": "",
        "name": "西双版纳嘎洒国际机场",
        "city": "西双版纳",
        "city_code": "JHG",
        "province": "云南",
        "level": "",
        "latitude": "21.97",
        "longitude": "100.77",
        "website": ""
    },
    {
        "id": "293",
        "IATA": "JIU",
        "ICAO": "",
        "name": "九江庐山机场",
        "city": "九江",
        "city_code": "JIU",
        "province": "江西",
        "level": "",
        "latitude": "29.7",
        "longitude": "115.97",
        "website": ""
    },
    {
        "id": "294",
        "IATA": "HZH",
        "ICAO": "",
        "name": "黎平机场",
        "city": "黎平",
        "city_code": "HZH",
        "province": "贵州",
        "level": "",
        "latitude": "26.32",
        "longitude": "109.15",
        "website": ""
    },
    {
        "id": "295",
        "IATA": "JIQ",
        "ICAO": "",
        "name": "黔江武陵山机场",
        "city": "黔江",
        "city_code": "JIQ",
        "province": "重庆",
        "level": "",
        "latitude": "29.52",
        "longitude": "108.83",
        "website": ""
    },
    {
        "id": "296",
        "IATA": "IQN",
        "ICAO": "",
        "name": "庆阳西峰机场",
        "city": "庆阳",
        "city_code": "IQN",
        "province": "甘肃",
        "level": "",
        "latitude": "35.8",
        "longitude": "107.6",
        "website": ""
    },
    {
        "id": "297",
        "IATA": "HYN",
        "ICAO": "",
        "name": "台州路桥机场",
        "city": "台州",
        "city_code": "HYN",
        "province": "浙江",
        "level": "",
        "latitude": "28.56",
        "longitude": "121.42",
        "website": ""
    },
    {
        "id": "298",
        "IATA": "HSN",
        "ICAO": "",
        "name": "舟山普陀山机场",
        "city": "舟山",
        "city_code": "HSN",
        "province": "浙江",
        "level": "",
        "latitude": "29.94",
        "longitude": "122.36",
        "website": ""
    },
    {
        "id": "299",
        "IATA": "HXD",
        "ICAO": "",
        "name": "德令哈机场",
        "city": "德令哈",
        "city_code": "HXD",
        "province": "青海",
        "level": "",
        "latitude": "37.12",
        "longitude": "97.27",
        "website": ""
    },
    {
        "id": "300",
        "IATA": "JUH",
        "ICAO": "",
        "name": "池州九华山机场",
        "city": "池州",
        "city_code": "JUH",
        "province": "安徽",
        "level": "",
        "latitude": "30.77",
        "longitude": "117.74",
        "website": ""
    },
    {
        "id": "301",
        "IATA": "KOW",
        "ICAO": "",
        "name": "赣州黄金机场",
        "city": "赣州",
        "city_code": "KOW",
        "province": "江西",
        "level": "",
        "latitude": "25.85",
        "longitude": "114.78",
        "website": ""
    },
    {
        "id": "302",
        "IATA": "JXA",
        "ICAO": "",
        "name": "鸡西兴凯湖机场",
        "city": "鸡西",
        "city_code": "JXA",
        "province": "黑龙江",
        "level": "",
        "latitude": "45.31",
        "longitude": "131",
        "website": ""
    },
    {
        "id": "303",
        "IATA": "KJH",
        "ICAO": "",
        "name": "凯里黄屏机场",
        "city": "凯里",
        "city_code": "KJH",
        "province": "贵州",
        "level": "",
        "latitude": "26.97",
        "longitude": "107.99",
        "website": ""
    },
    {
        "id": "304",
        "IATA": "KGT",
        "ICAO": "",
        "name": "康定机场",
        "city": "康定",
        "city_code": "KGT",
        "province": "四川",
        "level": "",
        "latitude": "30.13",
        "longitude": "101.75",
        "website": ""
    },
    {
        "id": "305",
        "IATA": "KRY",
        "ICAO": "",
        "name": "克拉玛依机场",
        "city": "克拉玛依",
        "city_code": "KRY",
        "province": "新疆",
        "level": "",
        "latitude": "45.62",
        "longitude": "84.88",
        "website": ""
    },
    {
        "id": "306",
        "IATA": "KHG",
        "ICAO": "",
        "name": "喀什机场",
        "city": "喀什",
        "city_code": "KHG",
        "province": "新疆",
        "level": "",
        "latitude": "39.54",
        "longitude": "76.01",
        "website": ""
    },
    {
        "id": "307",
        "IATA": "KRL",
        "ICAO": "",
        "name": "库尔勒机场",
        "city": "库尔勒",
        "city_code": "KRL",
        "province": "新疆",
        "level": "",
        "latitude": "41.62",
        "longitude": "86.14",
        "website": ""
    },
    {
        "id": "308",
        "IATA": "KCA",
        "ICAO": "",
        "name": "库车龟兹机场",
        "city": "库车",
        "city_code": "KCA",
        "province": "新疆",
        "level": "",
        "latitude": "41.17",
        "longitude": "83.7",
        "website": ""
    },
    {
        "id": "309",
        "IATA": "LCX",
        "ICAO": "",
        "name": "龙岩冠豸山机场",
        "city": "龙岩",
        "city_code": "LCX",
        "province": "福建",
        "level": "",
        "latitude": "25.68",
        "longitude": "116.75",
        "website": ""
    },
    {
        "id": "310",
        "IATA": "JUZ",
        "ICAO": "",
        "name": "衢州机场",
        "city": "衢州",
        "city_code": "JUZ",
        "province": "浙江",
        "level": "",
        "latitude": "28.97",
        "longitude": "118.83",
        "website": ""
    },
    {
        "id": "311",
        "IATA": "JZH",
        "ICAO": "",
        "name": "九寨黄龙机场",
        "city": "九寨沟",
        "city_code": "JZH",
        "province": "四川",
        "level": "",
        "latitude": "32.86",
        "longitude": "103.68",
        "website": ""
    },
    {
        "id": "312",
        "IATA": "LYG",
        "ICAO": "",
        "name": "连云港白塔埠机场",
        "city": "连云港",
        "city_code": "LYG",
        "province": "江苏",
        "level": "",
        "latitude": "34.57",
        "longitude": "118.88",
        "website": ""
    },
    {
        "id": "313",
        "IATA": "LLB",
        "ICAO": "",
        "name": "荔波机场",
        "city": "荔波",
        "city_code": "LLB",
        "province": "贵州",
        "level": "",
        "latitude": "25.45",
        "longitude": "107.96",
        "website": ""
    },
    {
        "id": "314",
        "IATA": "LJG",
        "ICAO": "",
        "name": "丽江三义机场",
        "city": "丽江",
        "city_code": "LJG",
        "province": "云南",
        "level": "",
        "latitude": "26.67",
        "longitude": "100.24",
        "website": ""
    },
    {
        "id": "315",
        "IATA": "LNJ",
        "ICAO": "",
        "name": "临沧机场",
        "city": "临沧",
        "city_code": "LNJ",
        "province": "云南",
        "level": "",
        "latitude": "23.74",
        "longitude": "100.03",
        "website": ""
    },
    {
        "id": "316",
        "IATA": "LYI",
        "ICAO": "",
        "name": "临邑机场",
        "city": "临沂",
        "city_code": "LYI",
        "province": "山东",
        "level": "",
        "latitude": "35.05",
        "longitude": "118.41",
        "website": ""
    },
    {
        "id": "317",
        "IATA": "LZH",
        "ICAO": "",
        "name": "柳州白莲机场",
        "city": "柳州",
        "city_code": "LZH",
        "province": "广西",
        "level": "",
        "latitude": "24.21",
        "longitude": "109.4",
        "website": ""
    },
    {
        "id": "318",
        "IATA": "LYA",
        "ICAO": "",
        "name": "洛阳北郊机场",
        "city": "洛阳",
        "city_code": "LYA",
        "province": "河南",
        "level": "",
        "latitude": "34.74",
        "longitude": "112.39",
        "website": ""
    },
    {
        "id": "319",
        "IATA": "LZO",
        "ICAO": "",
        "name": "泸州蓝田机场",
        "city": "泸州",
        "city_code": "LZO",
        "province": "四川",
        "level": "",
        "latitude": "29.03",
        "longitude": "105.47",
        "website": ""
    },
    {
        "id": "320",
        "IATA": "LUM",
        "ICAO": "",
        "name": "德宏芒市机场",
        "city": "芒市",
        "city_code": "LUM",
        "province": "云南",
        "level": "",
        "latitude": "24.41",
        "longitude": "98.53",
        "website": ""
    },
    {
        "id": "321",
        "IATA": "MDG",
        "ICAO": "",
        "name": "牡丹江海浪机场",
        "city": "牡丹江",
        "city_code": "MDG",
        "province": "黑龙江",
        "level": "",
        "latitude": "44.53",
        "longitude": "129.58",
        "website": ""
    },
    {
        "id": "322",
        "IATA": "LZY",
        "ICAO": "",
        "name": "林芝米林机场",
        "city": "林芝",
        "city_code": "LZY",
        "province": "西藏",
        "level": "",
        "latitude": "29.31",
        "longitude": "94.34",
        "website": ""
    },
    {
        "id": "323",
        "IATA": "LDS",
        "ICAO": "",
        "name": "伊春林都机场",
        "city": "伊春",
        "city_code": "LDS",
        "province": "黑龙江",
        "level": "",
        "latitude": "47.75",
        "longitude": "129.02",
        "website": ""
    },
    {
        "id": "324",
        "IATA": "LLF",
        "ICAO": "",
        "name": "永州零陵机场",
        "city": "永州",
        "city_code": "LLF",
        "province": "湖南",
        "level": "",
        "latitude": "26.35",
        "longitude": "111.61",
        "website": ""
    },
    {
        "id": "325",
        "IATA": "NBS",
        "ICAO": "",
        "name": "长白山机场",
        "city": "长白山",
        "city_code": "NBS",
        "province": "吉林",
        "level": "",
        "latitude": "42.08",
        "longitude": "127.6",
        "website": ""
    },
    {
        "id": "326",
        "IATA": "MXZ",
        "ICAO": "",
        "name": "梅县机场",
        "city": "梅县",
        "city_code": "MXZ",
        "province": "广东",
        "level": "",
        "latitude": "24.27",
        "longitude": "116.1",
        "website": ""
    },
    {
        "id": "327",
        "IATA": "MIG",
        "ICAO": "",
        "name": "绵阳南郊机场",
        "city": "绵阳",
        "city_code": "MIG",
        "province": "四川",
        "level": "",
        "latitude": "31.43",
        "longitude": "104.75",
        "website": ""
    },
    {
        "id": "328",
        "IATA": "NAO",
        "ICAO": "",
        "name": "南充高坪机场",
        "city": "南充",
        "city_code": "NAO",
        "province": "四川",
        "level": "",
        "latitude": "30.8",
        "longitude": "106.16",
        "website": ""
    },
    {
        "id": "329",
        "IATA": "NDG",
        "ICAO": "",
        "name": "齐齐哈尔机场",
        "city": "齐齐哈尔",
        "city_code": "NDG",
        "province": "黑龙江",
        "level": "",
        "latitude": "47.32",
        "longitude": "123.92",
        "website": ""
    },
    {
        "id": "330",
        "IATA": "NGQ",
        "ICAO": "",
        "name": "阿里昆莎机场",
        "city": "阿里",
        "city_code": "NGQ",
        "province": "西藏",
        "level": "",
        "latitude": "32.1",
        "longitude": "80.05",
        "website": ""
    },
    {
        "id": "331",
        "IATA": "OHE",
        "ICAO": "",
        "name": "漠河机场",
        "city": "漠河",
        "city_code": "OHE",
        "province": "东北",
        "level": "",
        "latitude": "52.92",
        "longitude": "122.42",
        "website": ""
    },
    {
        "id": "332",
        "IATA": "NTG",
        "ICAO": "",
        "name": "南通兴东机场",
        "city": "南通",
        "city_code": "NTG",
        "province": "江苏",
        "level": "",
        "latitude": "32.07",
        "longitude": "120.98",
        "website": ""
    },
    {
        "id": "333",
        "IATA": "NNY",
        "ICAO": "",
        "name": "南阳姜营机场",
        "city": "南阳",
        "city_code": "NNY",
        "province": "河南",
        "level": "",
        "latitude": "32.98",
        "longitude": "112.61",
        "website": ""
    },
    {
        "id": "334",
        "IATA": "RHT",
        "ICAO": "",
        "name": "阿拉善右旗巴丹吉林机场",
        "city": "阿拉善右旗",
        "city_code": "RHT",
        "province": "内蒙古",
        "level": "",
        "latitude": "39.21",
        "longitude": "101.64",
        "website": ""
    },
    {
        "id": "335",
        "IATA": "PZI",
        "ICAO": "",
        "name": "攀枝花保安营机场",
        "city": "攀枝花",
        "city_code": "PZI",
        "province": "四川",
        "level": "",
        "latitude": "26.54",
        "longitude": "101.79",
        "website": ""
    },
    {
        "id": "336",
        "IATA": "SYM",
        "ICAO": "",
        "name": "思茅机场",
        "city": "普洱",
        "city_code": "SYM",
        "province": "云南",
        "level": "",
        "latitude": "22.8",
        "longitude": "100.96",
        "website": ""
    },
    {
        "id": "337",
        "IATA": "TCG",
        "ICAO": "",
        "name": "塔城机场",
        "city": "塔城",
        "city_code": "TCG",
        "province": "新疆",
        "level": "",
        "latitude": "46.67",
        "longitude": "83.34",
        "website": ""
    },
    {
        "id": "338",
        "IATA": "TCZ",
        "ICAO": "",
        "name": "腾冲驼峰机场",
        "city": "腾冲",
        "city_code": "TCZ",
        "province": "云南",
        "level": "",
        "latitude": "24.94",
        "longitude": "98.48",
        "website": ""
    },
    {
        "id": "339",
        "IATA": "THQ",
        "ICAO": "",
        "name": "天水麦积山机场",
        "city": "天水",
        "city_code": "THQ",
        "province": "甘肃",
        "level": "",
        "latitude": "34.56",
        "longitude": "105.87",
        "website": ""
    },
    {
        "id": "340",
        "IATA": "TGO",
        "ICAO": "",
        "name": "通辽机场",
        "city": "通辽",
        "city_code": "TGO",
        "province": "内蒙古",
        "level": "",
        "latitude": "43.56",
        "longitude": "122.2",
        "website": ""
    },
    {
        "id": "341",
        "IATA": "TEN",
        "ICAO": "",
        "name": "铜仁凤凰机场",
        "city": "铜仁",
        "city_code": "TEN",
        "province": "贵州",
        "level": "",
        "latitude": "27.88",
        "longitude": "109.3",
        "website": ""
    },
    {
        "id": "342",
        "IATA": "TNH",
        "ICAO": "",
        "name": "三源浦机场",
        "city": "通化",
        "city_code": "TNH",
        "province": "吉林",
        "level": "",
        "latitude": "42.25",
        "longitude": "125.7",
        "website": ""
    },
    {
        "id": "343",
        "IATA": "TVS",
        "ICAO": "",
        "name": "唐山三女河机场",
        "city": "唐山",
        "city_code": "TVS",
        "province": "河北",
        "level": "",
        "latitude": "39.72",
        "longitude": "118",
        "website": ""
    },
    {
        "id": "344",
        "IATA": "WEH",
        "ICAO": "",
        "name": "大水泊机场",
        "city": "威海",
        "city_code": "WEH",
        "province": "山东",
        "level": "",
        "latitude": "37.19",
        "longitude": "122.24",
        "website": ""
    },
    {
        "id": "345",
        "IATA": "UYN",
        "ICAO": "",
        "name": "榆林榆阳机场",
        "city": "榆林",
        "city_code": "UYN",
        "province": "陕西",
        "level": "",
        "latitude": "38.36",
        "longitude": "109.6",
        "website": ""
    },
    {
        "id": "346",
        "IATA": "WXN",
        "ICAO": "",
        "name": "万州吴桥机场",
        "city": "万州",
        "city_code": "WXN",
        "province": "重庆",
        "level": "",
        "latitude": "30.8",
        "longitude": "108.43",
        "website": ""
    },
    {
        "id": "347",
        "IATA": "WNH",
        "ICAO": "",
        "name": "文山机场",
        "city": "文山",
        "city_code": "WNH",
        "province": "云南",
        "level": "",
        "latitude": "23.57",
        "longitude": "104.33",
        "website": ""
    },
    {
        "id": "348",
        "IATA": "WUA",
        "ICAO": "",
        "name": "乌海机场",
        "city": "乌海",
        "city_code": "WUA",
        "province": "内蒙古",
        "level": "",
        "latitude": "39.79",
        "longitude": "106.8",
        "website": ""
    },
    {
        "id": "349",
        "IATA": "WUS",
        "ICAO": "",
        "name": "武夷山机场",
        "city": "武夷山",
        "city_code": "WUS",
        "province": "福建",
        "level": "",
        "latitude": "27.7",
        "longitude": "118",
        "website": ""
    },
    {
        "id": "350",
        "IATA": "WUZ",
        "ICAO": "",
        "name": "长洲岛机场",
        "city": "梧州",
        "city_code": "WUZ",
        "province": "广西",
        "level": "",
        "latitude": "23.4",
        "longitude": "111.1",
        "website": ""
    },
    {
        "id": "351",
        "IATA": "XFN",
        "ICAO": "",
        "name": "襄阳机场",
        "city": "襄阳",
        "city_code": "XFN",
        "province": "湖北",
        "level": "",
        "latitude": "32.15",
        "longitude": "112.29",
        "website": ""
    },
    {
        "id": "352",
        "IATA": "XIC",
        "ICAO": "",
        "name": "西昌青山机场",
        "city": "西昌",
        "city_code": "XIC",
        "province": "四川",
        "level": "",
        "latitude": "27.98",
        "longitude": "102.19",
        "website": ""
    },
    {
        "id": "353",
        "IATA": "XIL",
        "ICAO": "",
        "name": "锡林浩特机场",
        "city": "锡林浩特",
        "city_code": "XIL",
        "province": "内蒙古",
        "level": "",
        "latitude": "43.92",
        "longitude": "115.96",
        "website": ""
    },
    {
        "id": "354",
        "IATA": "XNN",
        "ICAO": "",
        "name": "西宁曹家堡机场",
        "city": "西宁",
        "city_code": "XNN",
        "province": "青海",
        "level": "",
        "latitude": "36.53",
        "longitude": "102.04",
        "website": ""
    },
    {
        "id": "355",
        "IATA": "YBP",
        "ICAO": "",
        "name": "宜宾菜坝机场",
        "city": "宜宾",
        "city_code": "YBP",
        "province": "四川",
        "level": "",
        "latitude": "28.8",
        "longitude": "104.54",
        "website": ""
    },
    {
        "id": "356",
        "IATA": "YCU",
        "ICAO": "",
        "name": "运城关公机场",
        "city": "运城",
        "city_code": "YCU",
        "province": "山西",
        "level": "",
        "latitude": "35.11",
        "longitude": "111.04",
        "website": ""
    },
    {
        "id": "357",
        "IATA": "YIE",
        "ICAO": "",
        "name": "阿尔山伊尔施机场",
        "city": "阿尔山",
        "city_code": "YIE",
        "province": "内蒙古",
        "level": "",
        "latitude": "47.31",
        "longitude": "119.91",
        "website": ""
    },
    {
        "id": "358",
        "IATA": "YNZ",
        "ICAO": "",
        "name": "盐城南洋国际机场",
        "city": "盐城",
        "city_code": "YNZ",
        "province": "江苏",
        "level": "",
        "latitude": "33.43",
        "longitude": "120.2",
        "website": ""
    },
    {
        "id": "359",
        "IATA": "YNJ",
        "ICAO": "",
        "name": "延吉朝阳川国际机场",
        "city": "延吉",
        "city_code": "YNJ",
        "province": "吉林",
        "level": "",
        "latitude": "42.89",
        "longitude": "129.44",
        "website": ""
    },
    {
        "id": "360",
        "IATA": "YIH",
        "ICAO": "",
        "name": "宜昌三峡机场",
        "city": "宜昌",
        "city_code": "YIH",
        "province": "湖北",
        "level": "",
        "latitude": "30.55",
        "longitude": "111.48",
        "website": ""
    },
    {
        "id": "361",
        "IATA": "YIC",
        "ICAO": "",
        "name": "宜春明月山机场",
        "city": "宜春",
        "city_code": "YIC",
        "province": "江西",
        "level": "",
        "latitude": "27.8",
        "longitude": "114.31",
        "website": ""
    },
    {
        "id": "362",
        "IATA": "YIN",
        "ICAO": "",
        "name": "伊宁机场",
        "city": "伊宁",
        "city_code": "YIN",
        "province": "新疆",
        "level": "",
        "latitude": "43.95",
        "longitude": "81.33",
        "website": ""
    },
    {
        "id": "363",
        "IATA": "YIW",
        "ICAO": "",
        "name": "义乌机场",
        "city": "义乌",
        "city_code": "YIW",
        "province": "浙江",
        "level": "",
        "latitude": "29.34",
        "longitude": "120.03",
        "website": ""
    },
    {
        "id": "364",
        "IATA": "YUS",
        "ICAO": "",
        "name": "玉树巴塘机场",
        "city": "玉树",
        "city_code": "YUS",
        "province": "青海",
        "level": "",
        "latitude": "32.84",
        "longitude": "97.04",
        "website": ""
    },
    {
        "id": "365",
        "IATA": "YZY",
        "ICAO": "",
        "name": "张掖甘州机场",
        "city": "张掖",
        "city_code": "YZY",
        "province": "甘肃",
        "level": "",
        "latitude": "38.8",
        "longitude": "100.68",
        "website": ""
    },
    {
        "id": "366",
        "IATA": "ZHA",
        "ICAO": "",
        "name": "湛江坡头机场",
        "city": "湛江",
        "city_code": "ZHA",
        "province": "广东",
        "level": "",
        "latitude": "21.21",
        "longitude": "110.36",
        "website": ""
    },
    {
        "id": "367",
        "IATA": "ZAT",
        "ICAO": "",
        "name": "邵通机场",
        "city": "昭通",
        "city_code": "ZAT",
        "province": "云南",
        "level": "",
        "latitude": "27.32",
        "longitude": "103.8",
        "website": ""
    },
    {
        "id": "368",
        "IATA": "ZHY",
        "ICAO": "",
        "name": "中卫沙坡头机场",
        "city": "中卫",
        "city_code": "ZHY",
        "province": "宁夏",
        "level": "",
        "latitude": "37.57",
        "longitude": "105.15",
        "website": ""
    },
    {
        "id": "369",
        "IATA": "ZQZ",
        "ICAO": "",
        "name": "张家口机场",
        "city": "张家口",
        "city_code": "ZQZ",
        "province": "河北",
        "level": "",
        "latitude": "40.74",
        "longitude": "114.93",
        "website": ""
    },
    {
        "id": "370",
        "IATA": "NLT",
        "ICAO": "",
        "name": "新源那拉提机场",
        "city": "那拉提",
        "city_code": "NLT",
        "province": "新疆",
        "level": "",
        "latitude": "43.43",
        "longitude": "83.38",
        "website": ""
    },
    {
        "id": "371",
        "IATA": "LPF",
        "ICAO": "",
        "name": "六盘水月照机场",
        "city": "六盘水",
        "city_code": "LPF",
        "province": "贵州",
        "level": "",
        "latitude": "26.59",
        "longitude": "104.96",
        "website": ""
    },
    {
        "id": "372",
        "IATA": "ZUH",
        "ICAO": "",
        "name": "珠海金湾机场",
        "city": "珠海",
        "city_code": "ZUH",
        "province": "广东",
        "level": "",
        "latitude": "22.01",
        "longitude": "113.37",
        "website": ""
    },
    {
        "id": "373",
        "IATA": "HNY",
        "ICAO": "",
        "name": "衡阳南岳机场",
        "city": "衡阳",
        "city_code": "HNY",
        "province": "湖南",
        "level": "",
        "latitude": "26.72",
        "longitude": "112.62",
        "website": ""
    },
    {
        "id": "374",
        "IATA": "NAY",
        "ICAO": "",
        "name": "北京南苑机场",
        "city": "北京",
        "city_code": "BJS",
        "province": "北京",
        "level": "1",
        "latitude": "39.78",
        "longitude": "116.39",
        "website": ""
    },
    {
        "id": "375",
        "IATA": "NZH",
        "ICAO": "",
        "name": "满洲里西郊机场",
        "city": "满洲里",
        "city_code": "NZH",
        "province": "内蒙古",
        "level": "",
        "latitude": "49.57",
        "longitude": "117.33",
        "website": ""
    },
    {
        "id": "376",
        "IATA": "HZG",
        "ICAO": "",
        "name": "汉中城固机场",
        "city": "汉中",
        "city_code": "HZG",
        "province": "陕西",
        "level": "",
        "latitude": "33.13",
        "longitude": "107.21",
        "website": ""
    },
    {
        "id": "377",
        "IATA": "WEF",
        "ICAO": "",
        "name": "潍坊机场",
        "city": "潍坊",
        "city_code": "WEF",
        "province": "山东",
        "level": "",
        "latitude": "36.64",
        "longitude": "119.11",
        "website": ""
    },
    {
        "id": "378",
        "IATA": "SQD",
        "ICAO": "",
        "name": "三清山机场",
        "city": "上饶",
        "city_code": "SQD",
        "province": "江西",
        "level": "",
        "latitude": "28.38",
        "longitude": "117.97",
        "website": ""
    },
    {
        "id": "379",
        "IATA": "JIL",
        "ICAO": "",
        "name": "吉林二台子机场",
        "city": "吉林",
        "city_code": "JIL",
        "province": "吉林",
        "level": "",
        "latitude": "43.87",
        "longitude": "126.65",
        "website": ""
    },
    {
        "id": "380",
        "IATA": "RIZ",
        "ICAO": "",
        "name": "日照山字河机场",
        "city": "日照",
        "city_code": "RIZ",
        "province": "山东",
        "level": "",
        "latitude": "35.39",
        "longitude": "119.34",
        "website": ""
    },
    {
        "id": "381",
        "IATA": "BHY",
        "ICAO": "",
        "name": "北海福城机场",
        "city": "北海",
        "city_code": "BHY",
        "province": "广西",
        "level": "",
        "latitude": "21.54",
        "longitude": "109.29",
        "website": ""
    },
    {
        "id": "382",
        "IATA": "GXH",
        "ICAO": "",
        "name": "甘南夏河机场",
        "city": "甘南",
        "city_code": "GXH",
        "province": "甘肃",
        "level": "",
        "latitude": "34.81",
        "longitude": "102.64",
        "website": ""
    },
    {
        "id": "383",
        "IATA": "JNZ",
        "ICAO": "",
        "name": "锦州小岭子机场",
        "city": "锦州",
        "city_code": "JNZ",
        "province": "辽宁",
        "level": "",
        "latitude": "40.96",
        "longitude": "121.28",
        "website": ""
    },
    {
        "id": "384",
        "IATA": "LXI",
        "ICAO": "",
        "name": "林西机场（这个机场没有名字）",
        "city": "林西",
        "city_code": "LXI",
        "province": "内蒙古",
        "level": "",
        "latitude": "43.6",
        "longitude": "118.03",
        "website": ""
    },
    {
        "id": "385",
        "IATA": "SHF",
        "ICAO": "",
        "name": "石河子花垣机场",
        "city": "石河子",
        "city_code": "SHF",
        "province": "新疆",
        "level": "",
        "latitude": "44.25",
        "longitude": "85.91",
        "website": ""
    },
    {
        "id": "386",
        "IATA": "FYJ",
        "ICAO": "",
        "name": "抚远东极机场",
        "city": "抚远",
        "city_code": "FYJ",
        "province": "黑龙江",
        "level": "",
        "latitude": "48.2",
        "longitude": "134.36",
        "website": ""
    },
    {
        "id": "387",
        "IATA": "WDS",
        "ICAO": "",
        "name": "武当山机场",
        "city": "十堰",
        "city_code": "WDS",
        "province": "湖北",
        "level": "",
        "latitude": "32.59",
        "longitude": "110.91",
        "website": ""
    },
    {
        "id": "388",
        "IATA": "DLC",
        "ICAO": "",
        "name": "大连周水子国际机场",
        "city": "大连",
        "city_code": "DLC",
        "province": "辽宁",
        "level": "1",
        "latitude": "38.96",
        "longitude": "121.54",
        "website": ""
    },
    {
        "id": "389",
        "IATA": "YKH",
        "ICAO": "",
        "name": "营口兰旗机场",
        "city": "营口",
        "city_code": "YKH",
        "province": "辽宁",
        "level": "",
        "latitude": "40.54",
        "longitude": "122.33",
        "website": ""
    },
    {
        "id": "390",
        "IATA": "LLV",
        "ICAO": "",
        "name": "吕梁大武机场",
        "city": "吕梁",
        "city_code": "LLV",
        "province": "山西",
        "level": "",
        "latitude": "37.68",
        "longitude": "111.14",
        "website": ""
    },
    {
        "id": "391",
        "IATA": "HTT",
        "ICAO": "",
        "name": "花土沟机场",
        "city": "花土沟",
        "city_code": "HTT",
        "province": "青海",
        "level": "",
        "latitude": "38.25",
        "longitude": "90.86",
        "website": ""
    },
    {
        "id": "392",
        "IATA": "LFQ",
        "ICAO": "",
        "name": "临汾乔李机场",
        "city": "临汾",
        "city_code": "LFQ",
        "province": "山西",
        "level": "",
        "latitude": "36.13",
        "longitude": "111.64",
        "website": ""
    },
    {
        "id": "393",
        "IATA": "WUT",
        "ICAO": "",
        "name": "忻州五台山机场",
        "city": "忻州",
        "city_code": "WUT",
        "province": "山西",
        "level": "",
        "latitude": "38.6",
        "longitude": "112.97",
        "website": ""
    },
    {
        "id": "394",
        "IATA": "HEK",
        "ICAO": "",
        "name": "黑河机场",
        "city": "黑河",
        "city_code": "HEK",
        "province": "黑龙江",
        "level": "",
        "latitude": "50.22",
        "longitude": "127.43",
        "website": ""
    },
    {
        "id": "395",
        "IATA": "BPE",
        "ICAO": "",
        "name": "秦皇岛北戴河机场",
        "city": "秦皇岛",
        "city_code": "BPE",
        "province": "河北",
        "level": "",
        "latitude": "39.67",
        "longitude": "119.06",
        "website": ""
    },
    {
        "id": "396",
        "IATA": "PVG",
        "ICAO": "",
        "name": "上海浦东国际机场",
        "city": "上海",
        "city_code": "SHA",
        "province": "上海",
        "level": "1",
        "latitude": "31.15",
        "longitude": "121.8",
        "website": ""
    },
    {
        "id": "397",
        "IATA": "BAR",
        "ICAO": "",
        "name": "琼海博鳌机场",
        "city": "琼海",
        "city_code": "BAR",
        "province": "海南",
        "level": "",
        "latitude": "19.14",
        "longitude": "110.45",
        "website": ""
    },
    {
        "id": "398",
        "IATA": "YTY",
        "ICAO": "",
        "name": "扬州台州机场",
        "city": "扬州",
        "city_code": "YTY",
        "province": "江苏",
        "level": "",
        "latitude": "32.56",
        "longitude": "119.72",
        "website": ""
    },
    {
        "id": "399",
        "IATA": "LHW",
        "ICAO": "",
        "name": "兰州中川机场",
        "city": "兰州",
        "city_code": "LHW",
        "province": "甘肃",
        "level": "",
        "latitude": "36.51",
        "longitude": "103.62",
        "website": ""
    },
    {
        "id": "400",
        "IATA": "XUZ",
        "ICAO": "",
        "name": "徐州观音国际机场",
        "city": "徐州",
        "city_code": "XUZ",
        "province": "江苏",
        "level": "",
        "latitude": "34.06",
        "longitude": "117.55",
        "website": ""
    },
    {
        "id": "401",
        "IATA": "XIY",
        "ICAO": "",
        "name": "西安咸阳国际机场",
        "city": "西安",
        "city_code": "SIA",
        "province": "陕西",
        "level": "1",
        "latitude": "34.44",
        "longitude": "108.76",
        "website": ""
    },
    {
        "id": "402",
        "IATA": "WUX",
        "ICAO": "",
        "name": "苏南硕放国际机场",
        "city": "无锡",
        "city_code": "WUX",
        "province": "江苏",
        "level": "",
        "latitude": "31.49",
        "longitude": "120.42",
        "website": ""
    },
    {
        "id": "403",
        "IATA": "XMN",
        "ICAO": "",
        "name": "厦门高崎国际机场",
        "city": "厦门",
        "city_code": "XMN",
        "province": "福建",
        "level": "1",
        "latitude": "24.54",
        "longitude": "118.13",
        "website": ""
    },
    {
        "id": "404",
        "IATA": "WNZ",
        "ICAO": "",
        "name": "温州龙湾国际机场",
        "city": "温州",
        "city_code": "WNZ",
        "province": "浙江",
        "level": "",
        "latitude": "27.92",
        "longitude": "120.85",
        "website": ""
    },
    {
        "id": "405",
        "IATA": "URC",
        "ICAO": "",
        "name": "乌鲁木齐地窝堡国际机场",
        "city": "乌鲁木齐",
        "city_code": "URC",
        "province": "新疆",
        "level": "",
        "latitude": "43.9",
        "longitude": "87.48",
        "website": ""
    },
    {
        "id": "406",
        "IATA": "TYN",
        "ICAO": "",
        "name": "太原武宿国际机场",
        "city": "太原",
        "city_code": "TYN",
        "province": "山西",
        "level": "",
        "latitude": "37.75",
        "longitude": "112.63",
        "website": ""
    },
    {
        "id": "407",
        "IATA": "TSN",
        "ICAO": "",
        "name": "天津滨海国际机场",
        "city": "天津",
        "city_code": "TSN",
        "province": "天津",
        "level": "",
        "latitude": "39.13",
        "longitude": "117.36",
        "website": ""
    },
    {
        "id": "408",
        "IATA": "SZX",
        "ICAO": "",
        "name": "深圳市宝安国际机场",
        "city": "深圳",
        "city_code": "SZX",
        "province": "深圳",
        "level": "1",
        "latitude": "22.64",
        "longitude": "113.81",
        "website": ""
    },
    {
        "id": "409",
        "IATA": "SYX",
        "ICAO": "",
        "name": "凤凰国际机场",
        "city": "三亚",
        "city_code": "SYX",
        "province": "海南",
        "level": "1",
        "latitude": "18.31",
        "longitude": "109.41",
        "website": ""
    },
    {
        "id": "410",
        "IATA": "TAO",
        "ICAO": "",
        "name": "青岛国际机场",
        "city": "青岛",
        "city_code": "TAO",
        "province": "山东",
        "level": "",
        "latitude": "36.27",
        "longitude": "120.38",
        "website": ""
    },
    {
        "id": "411",
        "IATA": "TNA",
        "ICAO": "",
        "name": "遥墙国际机场",
        "city": "济南",
        "city_code": "TNA",
        "province": "山东",
        "level": "",
        "latitude": "36.86",
        "longitude": "117.21",
        "website": ""
    },
    {
        "id": "412",
        "IATA": "SWA",
        "ICAO": "",
        "name": "揭阳潮汕国际机场",
        "city": "揭阳",
        "city_code": "SWA",
        "province": "广东",
        "level": "",
        "latitude": "23.55",
        "longitude": "116.51",
        "website": ""
    },
    {
        "id": "413",
        "IATA": "SJW",
        "ICAO": "",
        "name": "石家庄正定国际机场",
        "city": "石家庄",
        "city_code": "SJW",
        "province": "河北",
        "level": "",
        "latitude": "38.28",
        "longitude": "114.69",
        "website": ""
    },
    {
        "id": "414",
        "IATA": "SHE",
        "ICAO": "",
        "name": "沈阳桃仙国际机场",
        "city": "沈阳",
        "city_code": "SHE",
        "province": "辽宁",
        "level": "",
        "latitude": "41.63",
        "longitude": "123.49",
        "website": ""
    },
    {
        "id": "415",
        "IATA": "SHA",
        "ICAO": "",
        "name": "上海虹桥国际机场",
        "city": "上海",
        "city_code": "SHA",
        "province": "上海",
        "level": "1",
        "latitude": "31.2",
        "longitude": "121.33",
        "website": ""
    },
    {
        "id": "416",
        "IATA": "PEK",
        "ICAO": "",
        "name": "北京首都国际机场",
        "city": "北京",
        "city_code": "BJS",
        "province": "北京",
        "level": "1",
        "latitude": "40.08",
        "longitude": "116.59",
        "website": ""
    },
    {
        "id": "417",
        "IATA": "NGB",
        "ICAO": "",
        "name": "宁波栎社国际机场",
        "city": "宁波",
        "city_code": "NGB",
        "province": "浙江",
        "level": "",
        "latitude": "29.82",
        "longitude": "121.46",
        "website": ""
    },
    {
        "id": "418",
        "IATA": "NNG",
        "ICAO": "",
        "name": "南宁吴圩国际机场",
        "city": "南宁",
        "city_code": "NNG",
        "province": "广西",
        "level": "",
        "latitude": "22.61",
        "longitude": "108.17",
        "website": ""
    },
    {
        "id": "419",
        "IATA": "NKG",
        "ICAO": "",
        "name": "南京禄口国际机场",
        "city": "南京",
        "city_code": "NKG",
        "province": "江苏",
        "level": "",
        "latitude": "31.74",
        "longitude": "118.87",
        "website": ""
    },
    {
        "id": "420",
        "IATA": "LXA",
        "ICAO": "",
        "name": "拉萨贡嘎机场",
        "city": "拉萨",
        "city_code": "LXA",
        "province": "西藏",
        "level": "",
        "latitude": "29.29",
        "longitude": "90.9",
        "website": ""
    },
    {
        "id": "421",
        "IATA": "KWL",
        "ICAO": "",
        "name": "桂林两江国际机场",
        "city": "桂林",
        "city_code": "KWL",
        "province": "广西",
        "level": "",
        "latitude": "25.22",
        "longitude": "110.05",
        "website": ""
    },
    {
        "id": "422",
        "IATA": "KHN",
        "ICAO": "",
        "name": "南昌昌北国际机场",
        "city": "南昌",
        "city_code": "KHN",
        "province": "江西",
        "level": "",
        "latitude": "28.86",
        "longitude": "115.91",
        "website": ""
    },
    {
        "id": "423",
        "IATA": "KMG",
        "ICAO": "",
        "name": "昆明长水国际机场",
        "city": "昆明",
        "city_code": "KMG",
        "province": "云南",
        "level": "",
        "latitude": "25.1",
        "longitude": "102.93",
        "website": ""
    },
    {
        "id": "424",
        "IATA": "KWE",
        "ICAO": "",
        "name": "贵阳龙洞堡国际机场",
        "city": "贵阳",
        "city_code": "KWE",
        "province": "贵州",
        "level": "",
        "latitude": "26.54",
        "longitude": "106.8",
        "website": ""
    },
    {
        "id": "425",
        "IATA": "JJN",
        "ICAO": "",
        "name": "泉州晋江国际机场",
        "city": "晋江",
        "city_code": "JJN",
        "province": "福建",
        "level": "",
        "latitude": "24.8",
        "longitude": "118.59",
        "website": ""
    },
    {
        "id": "426",
        "IATA": "HRB",
        "ICAO": "",
        "name": "哈尔滨太平国际机场",
        "city": "哈尔滨",
        "city_code": "HRB",
        "province": "黑龙江",
        "level": "",
        "latitude": "45.62",
        "longitude": "126.24",
        "website": ""
    },
    {
        "id": "427",
        "IATA": "HET",
        "ICAO": "",
        "name": "呼和浩特白塔国际机场",
        "city": "呼和浩特",
        "city_code": "HET",
        "province": "内蒙古",
        "level": "",
        "latitude": "40.85",
        "longitude": "111.81",
        "website": ""
    },
    {
        "id": "428",
        "IATA": "HGH",
        "ICAO": "",
        "name": "杭州萧山国际机场",
        "city": "杭州",
        "city_code": "HGH",
        "province": "浙江",
        "level": "1",
        "latitude": "30.24",
        "longitude": "120.43",
        "website": ""
    },
    {
        "id": "429",
        "IATA": "HAK",
        "ICAO": "",
        "name": "海口美兰国际机场",
        "city": "海口",
        "city_code": "HAK",
        "province": "海南",
        "level": "",
        "latitude": "19.94",
        "longitude": "110.46",
        "website": ""
    },
    {
        "id": "430",
        "IATA": "FOC",
        "ICAO": "",
        "name": "福州长乐国际机场",
        "city": "福州",
        "city_code": "FOC",
        "province": "福建",
        "level": "",
        "latitude": "25.93",
        "longitude": "119.67",
        "website": ""
    },
    {
        "id": "431",
        "IATA": "CTU",
        "ICAO": "",
        "name": "成都双流国际机场",
        "city": "成都",
        "city_code": "CTU",
        "province": "四川",
        "level": "1",
        "latitude": "30.58",
        "longitude": "103.96",
        "website": ""
    },
    {
        "id": "432",
        "IATA": "CKG",
        "ICAO": "",
        "name": "重庆江北国际机场",
        "city": "重庆",
        "city_code": "CKG",
        "province": "重庆",
        "level": "1",
        "latitude": "29.72",
        "longitude": "106.63",
        "website": ""
    },
    {
        "id": "433",
        "IATA": "CSX",
        "ICAO": "",
        "name": "长沙黄花国际机场",
        "city": "长沙",
        "city_code": "CSX",
        "province": "湖南",
        "level": "",
        "latitude": "28.19",
        "longitude": "113.21",
        "website": ""
    },
    {
        "id": "434",
        "IATA": "CGQ",
        "ICAO": "",
        "name": "长春龙嘉国际机场",
        "city": "长春",
        "city_code": "CGQ",
        "province": "吉林",
        "level": "",
        "latitude": "44",
        "longitude": "125.7",
        "website": ""
    },
    {
        "id": "435",
        "IATA": "HFE",
        "ICAO": "",
        "name": "合肥新桥国际机场",
        "city": "合肥",
        "city_code": "HFE",
        "province": "安徽",
        "level": "",
        "latitude": "31.99",
        "longitude": "116.97",
        "website": ""
    },
    {
        "id": "436",
        "IATA": "CAN",
        "ICAO": "",
        "name": "广州白云国际机场",
        "city": "广州",
        "city_code": "CAN",
        "province": "广东",
        "level": "1",
        "latitude": "23.39",
        "longitude": "113.3",
        "website": ""
    },
    {
        "id": "437",
        "IATA": "YNT",
        "ICAO": "",
        "name": "烟台莱山国际机场",
        "city": "烟台",
        "city_code": "YNT",
        "province": "山东",
        "level": "",
        "latitude": "37.66",
        "longitude": "120.99",
        "website": ""
    },
    {
        "id": "438",
        "IATA": "TXN",
        "ICAO": "",
        "name": "黄山机场",
        "city": "黄山",
        "city_code": "TXN",
        "province": "安徽",
        "level": "",
        "latitude": "29.73",
        "longitude": "118.26",
        "website": ""
    },
    {
        "id": "439",
        "IATA": "INC",
        "ICAO": "",
        "name": "银川河东国际机场",
        "city": "银川",
        "city_code": "INC",
        "province": "宁夏",
        "level": "",
        "latitude": "38.32",
        "longitude": "106.39",
        "website": ""
    },
    {
        "id": "440",
        "IATA": "CGO",
        "ICAO": "",
        "name": "郑州新郑国际机场",
        "city": "郑州",
        "city_code": "CGO",
        "province": "河南",
        "level": "",
        "latitude": "34.53",
        "longitude": "113.84",
        "website": ""
    },
    {
        "id": "441",
        "IATA": "DYG",
        "ICAO": "",
        "name": "张家界荷花国际机场",
        "city": "张家界",
        "city_code": "DYG",
        "province": "湖南",
        "level": "",
        "latitude": "29.11",
        "longitude": "110.45",
        "website": ""
    },
    {
        "id": "442",
        "IATA": "KJI",
        "ICAO": "",
        "name": "喀纳斯机场",
        "city": "布尔津",
        "city_code": "KJI",
        "province": "新疆",
        "level": "",
        "latitude": "48.22",
        "longitude": "87",
        "website": ""
    },
    {
        "id": "443",
        "IATA": "TLQ",
        "ICAO": "",
        "name": "吐鲁番交河机场",
        "city": "吐鲁番",
        "city_code": "TLQ",
        "province": "新疆",
        "level": "",
        "latitude": "43.02",
        "longitude": "89.07",
        "website": ""
    },
    {
        "id": "444",
        "IATA": "SQJ",
        "ICAO": "",
        "name": "三明沙县国际机场",
        "city": "三明",
        "city_code": "SQJ",
        "province": "福建",
        "level": "",
        "latitude": "26.43",
        "longitude": "117.83",
        "website": ""
    },
    {
        "id": "445",
        "IATA": "WUH",
        "ICAO": "",
        "name": "武汉天河国际机场",
        "city": "武汉",
        "city_code": "WUH",
        "province": "湖北",
        "level": "1",
        "latitude": "30.78",
        "longitude": "114.21",
        "website": ""
    },
    {
        "id": "446",
        "IATA": "DIG",
        "ICAO": "",
        "name": "迪庆香格里拉机场",
        "city": "迪庆",
        "city_code": "DIG",
        "province": "云南",
        "level": "",
        "latitude": "27.79",
        "longitude": "99.68",
        "website": ""
    },
    {
        "id": "447",
        "IATA": "NLH",
        "ICAO": "",
        "name": "泸沽湖机场",
        "city": "宁蒗",
        "city_code": "NLH",
        "province": "云南",
        "level": "",
        "latitude": "27.53",
        "longitude": "100.75",
        "website": ""
    },
    {
        "id": "448",
        "IATA": "DBC",
        "ICAO": "",
        "name": "拜城长安机场",
        "city": "白城",
        "city_code": "DBC",
        "province": "吉林",
        "level": "",
        "latitude": "45.51",
        "longitude": "123.02",
        "website": ""
    },
    {
        "id": "449",
        "IATA": "UCB",
        "ICAO": "",
        "name": "乌兰察布机场",
        "city": "乌兰察布",
        "city_code": "UCB",
        "province": "内蒙古",
        "level": "",
        "latitude": "41.13",
        "longitude": "113.11",
        "website": ""
    },
    {
        "id": "450",
        "IATA": "GMQ",
        "ICAO": "",
        "name": "果洛玛沁机场",
        "city": "果洛",
        "city_code": "GMQ",
        "province": "青海",
        "level": "",
        "latitude": "34.42",
        "longitude": "100.31",
        "website": ""
    },
    {
        "id": "451",
        "IATA": "CDE",
        "ICAO": "",
        "name": "承德普宁机场",
        "city": "承德",
        "city_code": "CDE",
        "province": "河北",
        "level": "",
        "latitude": "41.12",
        "longitude": "118.09",
        "website": ""
    },
    {
        "id": "452",
        "IATA": "HUO",
        "ICAO": "",
        "name": "霍林郭勒机场",
        "city": "霍林郭勒",
        "city_code": "HUO",
        "province": "内蒙古",
        "level": "",
        "latitude": "45.48",
        "longitude": "119.42",
        "website": ""
    },
    {
        "id": "453",
        "IATA": "LDG",
        "ICAO": "",
        "name": "列舒孔斯科耶机场",
        "city": "罗定",
        "city_code": "LUD",
        "province": "广东",
        "level": "",
        "latitude": "22.42",
        "longitude": "111.36",
        "website": ""
    },
    {
        "id": "454",
        "IATA": "FUG",
        "ICAO": "",
        "name": "阜阳西关机场",
        "city": "阜阳",
        "city_code": "FUG",
        "province": "安徽",
        "level": "",
        "latitude": "32.88",
        "longitude": "115.74",
        "website": ""
    },
    {
        "id": "455",
        "IATA": "IQM",
        "ICAO": "",
        "name": "且末玉都机场",
        "city": "且末",
        "city_code": "IQM",
        "province": "新疆",
        "level": "",
        "latitude": "38.13",
        "longitude": "85.53",
        "website": ""
    },
    {
        "id": "456",
        "IATA": "CWJ",
        "ICAO": "",
        "name": "沧源佤山机场",
        "city": "沧源",
        "city_code": "CWJ",
        "province": "云南",
        "level": "",
        "latitude": "23.28",
        "longitude": "99.37",
        "website": ""
    },
    {
        "id": "457",
        "IATA": "JMJ",
        "ICAO": "",
        "name": "澜沧景迈机场",
        "city": "澜沧",
        "city_code": "JMJ",
        "province": "云南",
        "level": "",
        "latitude": "22.42",
        "longitude": "99.78",
        "website": ""
    },
    {
        "id": "458",
        "IATA": "NZL",
        "ICAO": "",
        "name": "成吉思汗机场",
        "city": "扎兰屯",
        "city_code": "NZL",
        "province": "内蒙古",
        "level": "",
        "latitude": "47.88",
        "longitude": "122.77",
        "website": ""
    },
    {
        "id": "459",
        "IATA": "XYI",
        "ICAO": "",
        "name": "三沙永兴机场",
        "city": "三沙",
        "city_code": "LAC",
        "province": "海南",
        "level": "",
        "latitude": "16.83",
        "longitude": "112.34",
        "website": ""
    },
    {
        "id": "460",
        "IATA": "DTU",
        "ICAO": "",
        "name": "五大连池德都机场",
        "city": "五大连池",
        "city_code": "DTU",
        "province": "黑龙江",
        "level": "",
        "latitude": "48.43",
        "longitude": "126.1",
        "website": ""
    },
    {
        "id": "461",
        "IATA": "FYN",
        "ICAO": "",
        "name": "富蕴可可托海机场",
        "city": "富蕴",
        "city_code": "FYN",
        "province": "新疆",
        "level": "",
        "latitude": "46.8",
        "longitude": "89.51",
        "website": ""
    },
    {
        "id": "462",
        "IATA": "ZYI",
        "ICAO": "",
        "name": "遵义新舟机场",
        "city": "遵义",
        "city_code": "ZYI",
        "province": "贵州",
        "level": "",
        "latitude": "27.81",
        "longitude": "107.25",
        "website": ""
    },
    {
        "id": "463",
        "IATA": "JNG",
        "ICAO": "",
        "name": "济宁曲阜机场",
        "city": "济宁",
        "city_code": "JNG",
        "province": "山东",
        "level": "",
        "latitude": "35.29",
        "longitude": "116.35",
        "website": ""
    },
    {
        "id": "464",
        "IATA": "WGN",
        "ICAO": "",
        "name": "邵阳武冈机场",
        "city": "武冈",
        "city_code": "WGN",
        "province": "湖南",
        "level": "",
        "latitude": "26.8",
        "longitude": "110.65",
        "website": ""
    },
    {
        "id": "465",
        "IATA": "HUZ",
        "ICAO": "",
        "name": "惠州平潭机场",
        "city": "惠州",
        "city_code": "HUZ",
        "province": "广东",
        "level": "",
        "latitude": "23.05",
        "longitude": "114.61",
        "website": ""
    },
    {
        "id": "466",
        "IATA": "JSJ",
        "ICAO": "",
        "name": "建三江湿地机场",
        "city": "建三江",
        "city_code": "JSJ",
        "province": "黑龙江",
        "level": "",
        "latitude": "47.11",
        "longitude": "132.66",
        "website": ""
    },
    {
        "id": "467",
        "IATA": "QSZ",
        "ICAO": "",
        "name": "叶尔羌机场",
        "city": "莎车",
        "city_code": "QSZ",
        "province": "新疆",
        "level": "",
        "latitude": "38.25",
        "longitude": "77.06",
        "website": ""
    },
    {
        "id": "468",
        "IATA": "WMT",
        "ICAO": "",
        "name": "茅台机场",
        "city": "遵义",
        "city_code": "ZYI",
        "province": "贵州",
        "level": "",
        "latitude": "27.96",
        "longitude": "106.44",
        "website": ""
    }
]